# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel's tech posts
email: gabriel@utoctadel.com
description: > # this means to ignore newlines until "baseurl:"
  Experience is much better when it's shared! This blog collects some of it.
  Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gabmontes.github.io" # the base hostname & protocol for your site
twitter_username: gab_montes
github_username:  gabmontes

# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  input: GFM

# Front Matter settings
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
